# Generated by Django 5.0.3 on 2024-04-03 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Trainer full name"),
                ),
                ("date_of_birth", models.DateField(verbose_name="Date of birth")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Мужчина"), ("female", "Женщина")],
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "gyms",
                    models.CharField(
                        blank=True,
                        choices=[("gym1", "Gym1"), ("gym2", "Gym2"), ("gym3", "Gym3")],
                        max_length=100,
                        verbose_name="Gym name",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Spec"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
