# Generated by Django 5.0.3 on 2024-04-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trainers_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                max_length=10,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="specialization",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Specialization"
            ),
        ),
    ]
